### ISSUE TITLE
delete buf empty the svrIp

### ISSUE THREAD

**Issue by lee-jay** [NOLFXceptMe/http#1]
string HTTPProxy::getIp(const string& svrName)

There is a bug while getting responds from DNS Server. 
After "delete buf;", "inet_ntoa(addr_list[0])" becomes to be "0.0.0.0"
So modify these codes to:
    string ip_address = inet_ntoa(addr_list[0]);
    delete buf;
    return ip_address;

**Comment by NOLFXceptMe** [comment]
Thanks!
