### ISSUE TITLE
localfilename param

### ISSUE THREAD

**Issue by praveen-yadav** [NOLFXceptMe/http#2]
What are you expecting from localFileName parameter in following and why is it required:

> `./HTTPClientMain <method> <url> <localFileName> <direct/proxyaddress>`

**Comment by NOLFXceptMe** [comment]
`localFileName` is the name of the file from/into which content is read/written depending on the method being GET/PUT

**Comment by qrpengx** [comment]
how to use HTTPProxyMain

**Comment by NOLFXceptMe** [comment]
Hi @qrpengx, the new README should help you use HTTPProxyMain.
